import re 

leftParen = r"{"
rightParen = r"}"
typeInt = r"^[int]&"
typeString = r"string"
typeboolean = r"boolean"
equal = r"(==)"
notEqual = r"!="
boolFalse = r"false"
boolTrue = r"true"
assign = r"="
eop = r"\$"
character = r"(?:[a-z])"
# regex = r"([a-zA-Z]+) (\d+)"
